
modLoader="javafml"

loaderVersion="[40,)"

license="All Rights Reserved"

issueTrackerURL="https://github.com/Tiviacz1337/CloudBoots/issues"

[[mods]]

modId="cloudboots"

version="2.1.1"

displayName="Cloud Boots Mod"

updateJSONURL="https://gist.githubusercontent.com/Tiviacz1337/3f4df725e9107ae6093e07c498515d01/raw"

displayURL="https://www.curseforge.com/minecraft/mc-mods/cloud-boots-mod"

authors="Tiviacz1337"

description='Cloud Boots Mod for Minecraft 1.18.2!'